#ifndef FILESTATUS_HPP
#define FILESTATUS_HPP

enum class FileStatus {
    OK,
    FILE_NOT_FOUND,
    PERMISSION_DENIED,
    WRITE_ERROR,
    OPEN_ERROR,
    INSUFFICIENT_STOCK,
    TYPE_OPERATION_NOT_ALLOWED,
    ALREADY_EXISTS,
    NOT_FOUND,
    UNKNOWN_ERROR
};

#endif